# Generated by Django 4.0.5 on 2022-06-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_apellidos_alter_usuario_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_user',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
