# Generated by Django 4.0.5 on 2022-06-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manproducto',
            name='categoria_man',
            field=models.CharField(max_length=30, verbose_name='Tipo usuario'),
        ),
    ]
