# Generated by Django 4.0.5 on 2022-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_manproducto_categoria_man'),
    ]

    operations = [
        migrations.CreateModel(
            name='manBod',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ID PRODUCTO')),
                ('categoria_bod', models.CharField(max_length=30, verbose_name='Tipo usuario')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Producto')),
                ('cantidad', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
