# Generated by Django 4.0.5 on 2022-06-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vehiculo_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaProducto',
            fields=[
                ('idCategoriaProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoría Producto')),
                ('nombreCategoriaProducto', models.CharField(max_length=8, verbose_name='Nombre de la categoría Producto')),
            ],
        ),
        migrations.CreateModel(
            name='manBod',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ID PRODUCTO')),
                ('categoria_bod', models.CharField(max_length=30, verbose_name='Categoria')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Producto')),
                ('cantidad', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='manProducto',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ID PRODUCTO')),
                ('categoria_man', models.CharField(max_length=30, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Producto')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('precio', models.CharField(max_length=10, null=True, verbose_name='Precio')),
                ('descuentoSub', models.CharField(max_length=3, verbose_name='Descuento Sub')),
                ('descuentoOfe', models.CharField(max_length=3, verbose_name='Descuento Oferta')),
                ('imagen', models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_user', models.CharField(max_length=30, verbose_name='Tipo usuario')),
                ('rut', models.CharField(max_length=13, verbose_name='RUT')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=60, verbose_name='Dirección')),
                ('suscripcion', models.BooleanField(max_length=1, verbose_name='Con suscripción')),
                ('imagen', models.ImageField(default='cristian_gomez.jpg', upload_to='img/', verbose_name='Imagen')),
            ],
        ),
    ]
