# Generated by Django 4.0.5 on 2022-06-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vehiculo_desco_vehiculo_descs_alter_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
    ]
