# Generated by Django 4.0.5 on 2022-06-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_vehiculo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
    ]
