# Generated by Django 4.0.5 on 2022-07-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_tipouser_alter_usuario_tipo_user'),
        ('core', '0014_ventas'),
    ]

    operations = [
    ]
