# Generated by Django 4.0.5 on 2022-07-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20220704_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manbod',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ID PRODUCTO'),
        ),
    ]
