# Generated by Django 4.0.5 on 2022-07-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_manbod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manbod',
            name='cantidad',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='manbod',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
    ]
