# Generated by Django 4.0.5 on 2022-07-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_manbod_cantidad_alter_manbod_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manbod',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
